version = 1

[[annotations]]
path = [
  ".github/**",
  ".gitignore",
  "CLA.md",
  "README.md",
  "Cargo.toml",
  "Cargo.lock",
]
SPDX-FileCopyrightText = "2026 Nikolay Govorov <me@govorov.online>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
